version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install -r requirements.txt
    - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml

python:
  install:
  - requirements: requirements.txt
