site_name: rhododendron
repo_url: https://github.com/chabErch/rhododendron
# site_author: chaberch
# copyright: Copyright &copy; 2024 chaberch

nav:
  - Проблемы печати:
    - Карта: 'проблемы-печати/карта.md'
    - Слоновья нога L: 'проблемы-печати/слоновья-нога-l.md'
    - Слоновья нога H: 'проблемы-печати/слоновья-нога-h.md'
  - Contributing:
    - Инструментарий: 'contributing/инструментарий.md'

theme:
  name: material
  logo: assets/logo-24-24.svg
  favicon: assets/logo-24-24.svg
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: custom
    accent: custom

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/r3Dn.css
  - assets/stylesheets/print-site-r3Dn.css

markdown_extensions:
  - neoteroi.cards
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - toc:
      permalink: "#"
      toc_depth: 2
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search:
      lang: ru
  - print-site:
      add_to_navigation: true
      print_page_title: "На печать"
      add_cover_page: true
      cover_page_template: "docs/assets/templates/cover-page.tpl"
      toc_title: "Оглавление"
